### ISSUE TITLE
"npm test" is reporting errors in console

### ISSUE THREAD

**Issue by gabbersepp** [alfg/opendrinks#371]
**Describe the bug**
Execute:
- npm install
- npm test

Tests are green but there are errors in the console:

`      SyntaxError: Invalid or unexpected token
          at new Script (vm.js:79:7)
          at ScriptTransformer._transformAndBuildScript (C:\Users\jbiehler\Git\opendrinks\node_modules\jest-runtime\build\script_transformer.js:403:17)
          at ScriptTransformer.transform (C:\Users\jbiehler\Git\opendrinks\node_modules\jest-runtime\build\script_transformer.js:448:19)
          at Runtime._execModule (C:\Users\jbiehler\Git\opendrinks\node_modules\jest-runtime\build\index.js:640:53)
          at Runtime.requireModule (C:\Users\jbiehler\Git\opendrinks\node_modules\jest-runtime\build\index.js:376:14)
          at Runtime.requireModuleOrMock (C:\Users\jbiehler\Git\opendrinks\node_modules\jest-runtime\build\index.js:463:19)
          at require (C:\Users\jbiehler\Git\opendrinks\src\recipes\index.js:35:14)
          at getRecipe (C:\Users\jbiehler\Git\opendrinks\src\recipes\index.js:48:86)
          at func (C:\Users\jbiehler\Git\opendrinks\src\recipes\index.js:5:43)
          at Array.map (<anonymous>)`

This was tested with the current master branch.

**Comment by alfg** [comment]
Is this showing up in any of the CI builds too?

**Comment by gabbersepp** [comment]
> Is this showing up in any of the CI builds too?

Yes, for example have a look here:
https://travis-ci.org/alfg/opendrinks/jobs/597764841 (scroll own a bit). Not sure how I can add pictures in github, sry.

**Comment by alfg** [comment]
Ah, I see. I think it has something to do with a webpack file loader or something in tests. Interesting how it's on the `.jpeg` files, but not `.jpg`.

**Comment by alfg** [comment]
I can't check right now, but can you try adding `jpeg` to the regex on:
https://github.com/alfg/opendrinks/blob/master/jest.config.js#L5

**Comment by gabbersepp** [comment]
@alfg you are right. I did not have seen the config for jest-transform-stub. Works now after adding "jpeg" to the regex, too. So I removed the other code.
